! src/csv2json/main.f90
!
! Step 2 (Fortran): Numerical Processing
!
! Objective: isolated mathematical engine. Reads the CSV generated by C++ as a raw numerical matrix
! representing a grayscale image and applies the complete Canny pipeline:
!   1) Gaussian smoothing
!   2) gradient (Sobel 3x3, magnitude and direction)
!   3) non-maximum suppression
!   4) hysteresis thresholding
!   5) edge linking to produce ORDERED contours (not just isolated edge pixels)
!
! Input:  CSV file, one line per pixel row, values 0-255
! Output: JSON file (a missing ".json" extension is appended)
!
! JSON Schema:
! {
!   "width": 800,
!   "height": 600,
!   "edges": [
!       { "id": 1, "points": [ { "x": 10, "y": 15 }, { "x": 11, "y": 15 } ] }
!   ]
! }
!
! Rules:
!   width and height: integers, dimensions of the original image
!   edges: list of objects, each with:
!     id: integer, contour identifier (result of edge linking)
!     points: ORDERED list of `{x, y}` (integers, 0-based), in the order in which the
!             contour is traversed (consecutive points are 8-neighbours).
!
! Exit codes: 0 = OK, 1 = runtime error, 2 = usage error.
!
! Build: gfortran -O2 main.f90 -o csv2json      (uses the GNU extension `exit`)
!        (for tests, add: -g -fcheck=all)

program csv2json
    use, intrinsic :: iso_fortran_env, only: error_unit, output_unit
    implicit none

    integer, parameter :: dp = kind(1d0)
    real(dp), parameter :: PI = acos(-1d0)
    real(dp), parameter :: HIGH_RATIO = 0.20d0   ! high threshold = HIGH_RATIO * strongest edge
    real(dp), parameter :: LOW_RATIO = 0.40d0    ! low threshold  = LOW_RATIO * high threshold
    real(dp), parameter :: SOBEL_WEIGHTS(3) = [1d0, 2d0, 1d0]
    ! Neighbour offsets: 4-connected first, then diagonals (contours prefer straight steps).
    integer, parameter :: NB_DX(8) = [1, 0, -1, 0, 1, -1, -1, 1]
    integer, parameter :: NB_DY(8) = [0, 1, 0, -1, 1, 1, -1, -1]

    character(len=:), allocatable :: input_path, output_path
    real(dp), allocatable :: image(:, :), magnitude(:, :), direction(:, :), suppressed(:, :)
    logical, allocatable :: edges(:, :)
    real(dp) :: high

    call parse_args(input_path, output_path)

    call read_csv(input_path, image)
    write(output_unit, '(A)') 'CSV loaded: ' // input_path

    call sobel_gradient(gaussian_blur(image), magnitude, direction)
    suppressed = suppress_non_maxima(magnitude, direction)
    high = HIGH_RATIO * maxval(suppressed)
    edges = hysteresis(suppressed, LOW_RATIO * high, high)

    call write_json(output_path, edges)
    write(output_unit, '(A)') 'JSON successfully generated at: ' // output_path

contains

    ! CLI

    subroutine usage(unit)
        integer, intent(in) :: unit

        write(unit, '(A)') 'Usage: csv2json -i <input_path> -o <output_path>', &
            'Options:', &
            '  -h, --help            Print this help message and exit', &
            '  -i, --input <path>    Path to the input CSV file (required)', &
            '  -o, --output <path>   Path to the output JSON file (required)'
    end subroutine usage


    ! code: 1 = runtime error, 2 = usage error (also prints the usage)
    subroutine fail(message, code)
        character(len=*), intent(in) :: message
        integer, intent(in) :: code

        write(error_unit, '(A)') 'Error: ' // message
        if (code == 2) call usage(error_unit)
        call exit(code)
    end subroutine fail


    function str(n) result(s)
        integer, intent(in) :: n
        character(len=:), allocatable :: s
        character(len=20) :: buffer

        write(buffer, '(I0)') n
        s = trim(buffer)
    end function str


    function get_arg(i) result(value)
        integer, intent(in) :: i
        character(len=:), allocatable :: value
        integer :: n

        call get_command_argument(i, length=n)
        allocate(character(len=n) :: value)
        call get_command_argument(i, value)
    end function get_arg


    subroutine take_value(i, option, value)
        integer, intent(inout) :: i
        character(len=*), intent(in) :: option
        character(len=:), allocatable, intent(out) :: value

        i = i + 1
        if (i > command_argument_count()) call fail("option '" // option // "' requires a value", 2)
        value = get_arg(i)
    end subroutine take_value


    ! Case-insensitive suffix test.
    function has_extension(path, ext) result(found)
        character(len=*), intent(in) :: path, ext
        logical :: found
        character :: c
        integer :: k, offset

        found = .false.
        offset = len(path) - len(ext)
        if (offset < 0) return
        do k = 1, len(ext)
            c = path(offset + k:offset + k)
            if (c >= 'A' .and. c <= 'Z') c = achar(iachar(c) + 32)
            if (c /= ext(k:k)) return
        end do
        found = .true.
    end function has_extension


    subroutine parse_args(input_path, output_path)
        character(len=:), allocatable, intent(out) :: input_path, output_path
        character(len=:), allocatable :: arg
        integer :: i

        input_path = ''
        output_path = ''
        i = 1
        do while (i <= command_argument_count())
            arg = get_arg(i)
            select case (arg)
            case ('-h', '--help')
                call usage(output_unit)
                stop
            case ('-i', '--input')
                call take_value(i, arg, input_path)
            case ('-o', '--output')
                call take_value(i, arg, output_path)
            case default
                call fail("unknown argument '" // arg // "'", 2)
            end select
            i = i + 1
        end do

        if (len(input_path) == 0) call fail("option '-i,--input' is required", 2)
        if (len(output_path) == 0) call fail("option '-o,--output' is required", 2)
        if (.not. has_extension(output_path, '.json')) output_path = output_path // '.json'
    end subroutine parse_args


    ! CSV

    ! Next non-blank line, of any length (ios /= 0 at end of file).
    subroutine read_row(unit, line, lineno, ios)
        integer, intent(in) :: unit
        character(len=:), allocatable, intent(out) :: line
        integer, intent(inout) :: lineno
        integer, intent(out) :: ios
        character(len=4096) :: chunk
        integer :: n

        do
            line = ''
            do
                read(unit, '(A)', advance='no', iostat=ios, size=n) chunk
                if (ios == 0 .or. is_iostat_eor(ios)) line = line // chunk(1:n)
                if (ios /= 0) exit
            end do
            if (is_iostat_eor(ios)) ios = 0
            if (ios /= 0) return
            lineno = lineno + 1
            if (len_trim(line) > 0) return
        end do
    end subroutine read_row


    subroutine parse_row(line, row, lineno)
        character(len=*), intent(in) :: line
        real(dp), intent(out) :: row(:)
        integer, intent(in) :: lineno
        integer :: c, first, last, ios

        first = 1
        do c = 1, size(row)
            last = index(line(first:), ',')
            last = merge(len(line), first + last - 2, last == 0)
            row(c) = -1d0    ! also catches null values such as "/"
            read(line(first:last), *, iostat=ios) row(c)
            if (ios /= 0 .or. .not. (row(c) >= 0d0 .and. row(c) <= 255d0)) then
                call fail('CSV line ' // str(lineno) // ': column ' // str(c) // ' is not a number in 0-255', 1)
            end if
            first = last + 2
        end do
    end subroutine parse_row


    subroutine read_csv(path, matrix)
        character(len=*), intent(in) :: path
        real(dp), allocatable, intent(out) :: matrix(:, :)
        character(len=:), allocatable :: line
        character(len=256) :: msg
        integer :: unit, ios, lineno, nrows, ncols, cols, r

        open(newunit=unit, file=path, status='old', action='read', iostat=ios, iomsg=msg)
        if (ios /= 0) call fail("cannot open '" // path // "': " // trim(msg), 1)

        ! Pass 1: dimensions (every row must have as many columns as the first one).
        nrows = 0
        ncols = 0
        lineno = 0
        do
            call read_row(unit, line, lineno, ios)
            if (ios /= 0) exit
            cols = count([(line(r:r) == ',', r = 1, len(line))]) + 1
            if (nrows == 0) ncols = cols
            if (cols /= ncols) then
                call fail('CSV line ' // str(lineno) // ': found ' // str(cols) // ' columns, expected ' &
                          // str(ncols), 1)
            end if
            nrows = nrows + 1
        end do
        if (ios > 0) call fail("read error in '" // path // "'", 1)
        if (nrows == 0) call fail("empty CSV: '" // path // "'", 1)

        ! Pass 2: values.
        allocate(matrix(nrows, ncols))
        rewind(unit)
        lineno = 0
        do r = 1, nrows
            call read_row(unit, line, lineno, ios)
            if (ios /= 0) call fail("'" // path // "' changed while reading", 1)
            call parse_row(line, matrix(r, :), lineno)
        end do
        close(unit)
    end subroutine read_csv


    ! Canny

    function gaussian_blur(image) result(blurred)
        real(dp), intent(in) :: image(:, :)
        real(dp), allocatable :: blurred(:, :)
        real(dp), parameter :: KERNEL(3, 3) = reshape([1, 2, 1, 2, 4, 2, 1, 2, 1], [3, 3]) / 16d0
        real(dp) :: total
        integer :: x, y, dx, dy, h, w

        h = size(image, 1)
        w = size(image, 2)
        allocate(blurred, mold=image)
        do x = 1, w
            do y = 1, h
                total = 0d0
                do dx = -1, 1
                    do dy = -1, 1    ! border pixels are replicated
                        total = total + KERNEL(dy + 2, dx + 2) * image(min(h, max(1, y + dy)), min(w, max(1, x + dx)))
                    end do
                end do
                blurred(y, x) = total
            end do
        end do
    end function gaussian_blur


    ! Sobel 3x3 (y grows downwards). Border pixels are left at 0.
    subroutine sobel_gradient(image, magnitude, direction)
        real(dp), intent(in) :: image(:, :)
        real(dp), allocatable, intent(out) :: magnitude(:, :), direction(:, :)
        real(dp) :: sx, sy
        integer :: x, y

        allocate(magnitude(size(image, 1), size(image, 2)), direction(size(image, 1), size(image, 2)))
        magnitude = 0d0
        direction = 0d0
        do x = 2, size(image, 2) - 1
            do y = 2, size(image, 1) - 1
                sx = dot_product(SOBEL_WEIGHTS, image(y-1:y+1, x+1) - image(y-1:y+1, x-1))
                sy = dot_product(SOBEL_WEIGHTS, image(y+1, x-1:x+1) - image(y-1, x-1:x+1))
                magnitude(y, x) = sqrt(sx * sx + sy * sy)
                direction(y, x) = atan2(sy, sx)
            end do
        end do
    end subroutine sobel_gradient


    ! Keeps a pixel only if it is a local maximum along the gradient direction.
    function suppress_non_maxima(magnitude, direction) result(thin)
        real(dp), intent(in) :: magnitude(:, :), direction(:, :)
        real(dp), allocatable :: thin(:, :)
        real(dp) :: angle
        integer :: x, y, dx, dy

        allocate(thin, mold=magnitude)
        thin = 0d0
        do x = 2, size(thin, 2) - 1
            do y = 2, size(thin, 1) - 1
                angle = modulo(direction(y, x) * 180d0 / PI, 180d0)
                if (angle < 22.5d0 .or. angle >= 157.5d0) then
                    dx = 1; dy = 0
                else if (angle < 67.5d0) then
                    dx = 1; dy = 1
                else if (angle < 112.5d0) then
                    dx = 0; dy = 1
                else
                    dx = -1; dy = 1
                end if
                ! ">" on one side only, so a plateau of equal values keeps a single pixel.
                if (magnitude(y, x) > magnitude(y - dy, x - dx) .and. &
                    magnitude(y, x) >= magnitude(y + dy, x + dx)) thin(y, x) = magnitude(y, x)
            end do
        end do
    end function suppress_non_maxima


    ! Strong pixels (>= high) seed the edge map, which then grows through connected weak
    ! pixels (>= low). Linear time: every pixel enters the stack at most once.
    function hysteresis(strength, low, high) result(edges)
        real(dp), intent(in) :: strength(:, :), low, high
        logical, allocatable :: edges(:, :), candidate(:, :)
        integer, allocatable :: stack(:, :)
        integer :: top, x, y, dx, dy

        ! tiny() keeps zero-strength pixels out when the thresholds are 0 (flat image).
        ! Strength is 0 on the border (see suppress_non_maxima), so every candidate has all
        ! its 8 neighbours inside the array.
        candidate = strength >= max(low, tiny(low))
        edges = strength >= max(high, tiny(high))
        allocate(stack(2, count(candidate)))

        top = 0
        do x = 1, size(edges, 2)
            do y = 1, size(edges, 1)
                if (edges(y, x)) then
                    top = top + 1
                    stack(:, top) = [y, x]
                end if
            end do
        end do

        do while (top > 0)
            y = stack(1, top)
            x = stack(2, top)
            top = top - 1
            do dx = -1, 1
                do dy = -1, 1
                    if (edges(y + dy, x + dx) .or. .not. candidate(y + dy, x + dx)) cycle
                    edges(y + dy, x + dx) = .true.
                    top = top + 1
                    stack(:, top) = [y + dy, x + dx]
                end do
            end do
        end do
    end function hysteresis


    ! JSON

    ! Which of the 8 neighbours (in NB_DX/NB_DY order) are set.
    function neighbors(edges, y, x) result(mask)
        logical, intent(in) :: edges(:, :)
        integer, intent(in) :: y, x
        logical :: mask(8)
        integer :: k, yy, xx

        do k = 1, 8
            yy = y + NB_DY(k)
            xx = x + NB_DX(k)
            mask(k) = .false.
            if (yy >= 1 .and. yy <= size(edges, 1) .and. xx >= 1 .and. xx <= size(edges, 2)) mask(k) = edges(yy, xx)
        end do
    end function neighbors


    ! Walks one contour from (y, x), writing its points in traversal order and clearing them
    ! from the edge map.
    subroutine write_contour(unit, edges, id, y, x)
        integer, intent(in) :: unit, id, y, x
        logical, intent(inout) :: edges(:, :)
        integer :: cy, cx, k

        write(unit, '(A,I0,A)', advance='no') '  { "id": ', id, ', "points": [ '
        cy = y
        cx = x
        do
            edges(cy, cx) = .false.
            write(unit, '(A,I0,A,I0,A)', advance='no') '{ "x": ', cx - 1, ', "y": ', cy - 1, ' }'
            k = findloc(neighbors(edges, cy, cx), .true., dim=1)    ! 0 when the contour ends
            if (k == 0) exit
            cy = cy + NB_DY(k)
            cx = cx + NB_DX(k)
            write(unit, '(A)', advance='no') ', '
        end do
        write(unit, '(A)', advance='no') ' ] }'
    end subroutine write_contour


    ! Consumes the edge map: traced pixels are cleared.
    subroutine write_json(path, edges)
        character(len=*), intent(in) :: path
        logical, intent(inout) :: edges(:, :)
        character(len=256) :: msg
        integer :: unit, ios, pass, x, y, id

        open(newunit=unit, file=path, status='replace', action='write', iostat=ios, iomsg=msg)
        if (ios /= 0) call fail("cannot open '" // path // "': " // trim(msg), 1)

        write(unit, '(A,I0,A,I0,A)') '{ "width": ', size(edges, 2), ', "height": ', size(edges, 1), ', "edges": ['

        ! Pass 1 starts contours at open ends (a single neighbour) so they are traced end to
        ! end; pass 2 picks up what is left (closed loops).
        id = 0
        do pass = 1, 2
            do y = 1, size(edges, 1)
                do x = 1, size(edges, 2)
                    if (.not. edges(y, x)) cycle
                    if (pass == 1 .and. count(neighbors(edges, y, x)) > 1) cycle
                    id = id + 1
                    if (id > 1) write(unit, '(A)') ','
                    call write_contour(unit, edges, id, y, x)
                end do
            end do
        end do

        if (id > 0) write(unit, '(A)') ''
        write(unit, '(A)') '] }'
        close(unit)
    end subroutine write_json

end program csv2json
