! src/csv2json/main.f90
!
! Step 2 (Fortran): Numerical Processing
!
! Responsibility: isolated mathematical engine. Reads the CSV generated by C++ as a raw numerical matrix
! representing a grayscale image and applies the complete Canny pipeline:
!   1) Gaussian smoothing
!   2) gradient (Sobel 3x3, magnitude and direction)
!   3) non-maximum suppression
!   4) hysteresis thresholding
!   5) edge linking to produce ORDERED contours (not just isolated edge pixels)
!
! Input: CSV file, one line per pixel row, values ​​0-255
! Output: Specific JSON
!
! JSON Schema:
! {
!   "width": 800,
!   "height": 600,
!   "edges": [
!       { "id": 1, "points": [ { "x": 10, "y": 15 }, { "x": 11, "y": 15 } ] }
!   ]
! }
!
! Rules:
!   width and height: integers, dimensions of the original image
!   edges: list of objects, each with:
!     id: integer, contour identifier (result of edge linking)
!     points: ORDERED list of `{x, y}` (integers), in the order in which the
!             contour is traversed.

program csv2json
    implicit none

    character(len=*), parameter :: DEFAULT_OUTPUT_DIR = "output"
    character(len=*), parameter :: DEFAULT_OUTPUT_FILE = "step2.json"

    character(len=256) :: input_path, output_path
    character(len=1024) :: arg
    integer :: i, n_args
    logical :: show_help = .false.

    real(8), allocatable :: image(:, :), blurred(:, :)
    real(8), allocatable :: magnitude(:, :), direction(:, :)
    real(8), allocatable :: suppressed(:, :)
    logical, allocatable :: edges(:, :), visited(:, :)
    integer :: width, height, ios
    real(8) :: low_threshold, high_threshold

    input_path = ""
    output_path = ""

    ! Args
    n_args = command_argument_count()
    if (n_args == 0) then
        call usage()
        stop
    end if

    i = 1
    do while (i <= n_args)
        call get_command_argument(i, arg)
        select case (trim(arg))
        case ("-h", "--help")
            show_help = .true.
            exit
        case ("-i", "--input")
            if (i < n_args) then
                i = i + 1
                call get_command_argument(i, arg)
                input_path = trim(arg)
            end if
        case ("-o", "--output")
            if (i < n_args) then
                i = i + 1
                call get_command_argument(i, arg)
                output_path = trim(arg)
            end if
        end select
        i = i + 1
    end do

    if (show_help) then
        call usage()
        stop
    end if

    if (len_trim(input_path) == 0) then
        print *, "Error: The input argument (-i) is required."
        call usage()
        error stop 1
    end if

    if (len_trim(output_path) == 0) then
        output_path = find_or_resolve_output_dir(DEFAULT_OUTPUT_DIR) // "/" // DEFAULT_OUTPUT_FILE
    end if

    if (.not. validate_extension(input_path, ".csv")) then
        print *, "Error: The input file must have a .csv extension -> ", trim(input_path)
        error stop 1
    end if

    if (.not. validate_extension(output_path, ".json")) then
        print *, "Error: The output file must have the .json extension -> ", trim(output_path)
        error stop 1
    end if

    block
        logical :: exists
        inquire(file=input_path, exist=exists)
        if (.not. exists) then
            print *, "Error: The input file does not exist: ", trim(input_path)
            error stop 1
        end if
    end block

    ! CSV
    call read_csv(trim(input_path), image, width, height)
    print *, "CSV loaded: ", trim(input_path)

    allocate(blurred(height, width))
    allocate(magnitude(height, width))
    allocate(direction(height, width))
    allocate(suppressed(height, width))
    allocate(edges(height, width))
    allocate(visited(height, width))

    call gaussian_blur(image, blurred, width, height)
    call sobel_gradient(blurred, magnitude, direction, width, height)
    call non_maximum_suppression(magnitude, direction, suppressed, width, height)

    high_threshold = 0.20d0 * maxval(suppressed)
    low_threshold = 0.40d0 * high_threshold

    call hysteresis(suppressed, edges, width, height, &
                    low_threshold, high_threshold)

    ! JSON
    visited = .false.
    call write_json(trim(output_path), edges, visited, width, height)

    deallocate(image, blurred, magnitude, direction, suppressed)
    deallocate(edges, visited)

    print *, "JSON successfully generated at: ", trim(output_path)

contains

    subroutine usage()
        print *, "Usage: csv2json -i <input_path> [-o <output_path>]"
        print *, "Options:"
        print *, "  -h, --help            Print this help message and exit"
        print *, "  -i, --input <path>    Path to the input CSV file (required)"
        print *, "  -o, --output <path>   Path to the output JSON file (default: ", &
                 DEFAULT_OUTPUT_DIR, "/", DEFAULT_OUTPUT_FILE, ")"
    end subroutine usage


    function validate_extension(filename, ext) result(is_valid)
        character(len=*), intent(in) :: filename, ext
        logical :: is_valid
        integer :: len_f

        len_f = len_trim(filename)
        if (len_f > len(ext)) then
            is_valid = (filename(len_f - len(ext) + 1:len_f) == trim(ext))
        else
            is_valid = .false.
        end if
    end function validate_extension


    function find_or_resolve_output_dir(target_dir) result(resolved_path)
        character(len=*), intent(in) :: target_dir
        character(len=:), allocatable :: resolved_path
        character(len=1024) :: current_path, candidate
        logical :: dir_exists
        integer :: pos

        call getcwd(current_path)
        current_path = trim(current_path)

        do
            candidate = trim(current_path) // "/" // trim(target_dir)
            inquire(file=trim(candidate) // "/", exist=dir_exists)
            if (dir_exists) then
                resolved_path = trim(candidate)
                return
            end if

            pos = index(current_path, "/", back=.true.)
            if (pos == 0) pos = index(current_path, "\", back=.true.)

            if (pos <= 1) then
                exit
            end if
            current_path = current_path(1:pos-1)
        end do

        resolved_path = trim(target_dir)
        inquire(file=trim(resolved_path) // "/", exist=dir_exists)
        if (.not. dir_exists) then
            call execute_command_line("mkdir -p " // trim(resolved_path))
        end if
    end function find_or_resolve_output_dir


    subroutine read_csv(path, matrix, width, height)
        character(len=*), intent(in) :: path
        real(8), allocatable, intent(out) :: matrix(:, :)
        integer, intent(out) :: width, height

        character(len=8192) :: line
        integer :: unit, ios, ncols, nrows, i, j
        real(8), allocatable :: row(:)

        open(newunit=unit, file=path, status='old', action='read', &
             iostat=ios)
        if (ios /= 0) error stop 'cannot open input CSV'

        nrows = 0
        ncols = -1

        do
            read(unit, '(A)', iostat=ios) line
            if (ios /= 0) exit
            if (len_trim(line) == 0) cycle

            call parse_csv_line(trim(line), row, ncols)
            if (ncols < 0) error stop 'invalid CSV row'
            nrows = nrows + 1
            deallocate(row)
        end do

        if (nrows == 0 .or. ncols <= 0) error stop 'empty CSV'
        rewind(unit)

        width = ncols
        height = nrows
        allocate(matrix(height, width))

        i = 0
        do
            read(unit, '(A)', iostat=ios) line
            if (ios /= 0) exit
            if (len_trim(line) == 0) cycle

            i = i + 1
            call parse_csv_line(trim(line), row, ncols)
            matrix(i, :) = row
            deallocate(row)
        end do

        close(unit)
    end subroutine read_csv


    subroutine parse_csv_line(line, values, expected_cols)
        character(len=*), intent(in) :: line
        real(8), allocatable, intent(out) :: values(:)
        integer, intent(inout) :: expected_cols

        character(len=8192) :: token
        integer :: i, start, finish, count, ios
        real(8) :: value

        count = 1
        do i = 1, len_trim(line)
            if (line(i:i) == ',') count = count + 1
        end do

        if (expected_cols < 0) then
            expected_cols = count
        else if (count /= expected_cols) then
            error stop 'inconsistent CSV column count'
        end if

        allocate(values(count))
        start = 1

        do i = 1, count
            finish = index(line(start:), ',')
            if (finish == 0) then
                token = adjustl(line(start:))
            else
                token = adjustl(line(start:start+finish-2))
            end if

            read(token, *, iostat=ios) value
            if (ios /= 0) error stop 'invalid numeric value in CSV'
            values(i) = value

            if (finish == 0) exit
            start = start + finish
        end do
    end subroutine parse_csv_line


    subroutine gaussian_blur(input, output, width, height)
        integer, intent(in) :: width, height
        real(8), intent(in) :: input(height, width)
        real(8), intent(out) :: output(height, width)
        real(8), parameter :: kernel(3,3) = reshape([ &
            1d0, 2d0, 1d0, &
            2d0, 4d0, 2d0, &
            1d0, 2d0, 1d0], [3,3]) / 16d0
        integer :: x, y, dx, dy, xx, yy
        real(8) :: sum

        do y = 1, height
            do x = 1, width
                sum = 0d0
                do dy = -1, 1
                    do dx = -1, 1
                        xx = min(width, max(1, x + dx))
                        yy = min(height, max(1, y + dy))
                        sum = sum + input(yy, xx) * kernel(dy+2, dx+2)
                    end do
                end do
                output(y, x) = sum
            end do
        end do
    end subroutine gaussian_blur


    subroutine sobel_gradient(input, magnitude, direction, width, height)
        integer, intent(in) :: width, height
        real(8), intent(in) :: input(height, width)
        real(8), intent(out) :: magnitude(height, width)
        real(8), intent(out) :: direction(height, width)
        integer, parameter :: gx(3,3) = reshape([ &
            -1, 0, 1, -2, 0, 2, -1, 0, 1], [3,3])
        integer, parameter :: gy(3,3) = reshape([ &
            -1, -2, -1, 0, 0, 0, 1, 2, 1], [3,3])
        integer :: x, y, dx, dy, xx, yy
        real(8) :: sx, sy

        magnitude = 0d0
        direction = 0d0

        do y = 2, height - 1
            do x = 2, width - 1
                sx = 0d0
                sy = 0d0
                do dy = -1, 1
                    do dx = -1, 1
                        xx = x + dx
                        yy = y + dy
                        sx = sx + input(yy, xx) * gx(dy+2, dx+2)
                        sy = sy + input(yy, xx) * gy(dy+2, dx+2)
                    end do
                end do
                magnitude(y,x) = sqrt(sx*sx + sy*sy)
                direction(y,x) = atan2(sy, sx)
            end do
        end do
    end subroutine sobel_gradient


    subroutine non_maximum_suppression(magnitude, direction, output, width, height)
        integer, intent(in) :: width, height
        real(8), intent(in) :: magnitude(height, width)
        real(8), intent(in) :: direction(height, width)
        real(8), intent(out) :: output(height, width)
        integer :: x, y, sector
        real(8) :: angle, current, first, second

        output = 0d0

        do y = 2, height - 1
            do x = 2, width - 1
                angle = direction(y,x) * 180d0 / acos(-1d0)
                if (angle < 0d0) angle = angle + 180d0

                current = magnitude(y,x)

                if (angle < 22.5d0 .or. angle >= 157.5d0) then
                    first = magnitude(y,x-1)
                    second = magnitude(y,x+1)
                else if (angle < 67.5d0) then
                    first = magnitude(y-1,x+1)
                    second = magnitude(y+1,x-1)
                else if (angle < 112.5d0) then
                    first = magnitude(y-1,x)
                    second = magnitude(y+1,x)
                else
                    first = magnitude(y-1,x-1)
                    second = magnitude(y+1,x+1)
                end if

                if (current >= first .and. current >= second) then
                    output(y,x) = current
                end if
            end do
        end do
    end subroutine non_maximum_suppression


    subroutine hysteresis(input, output, width, height, low, high)
        integer, intent(in) :: width, height
        real(8), intent(in) :: input(height, width)
        logical, intent(out) :: output(height, width)
        real(8), intent(in) :: low, high
        integer :: x, y

        output = .false.

        do y = 2, height - 1
            do x = 2, width - 1
                if (input(y,x) >= high) then
                    output(y,x) = .true.
                end if
            end do
        end do

        do
            if (.not. grow_edges(input, output, width, height, low)) exit
        end do
    end subroutine hysteresis


    logical function grow_edges(input, output, width, height, low)
        integer, intent(in) :: width, height
        real(8), intent(in) :: input(height, width)
        logical, intent(inout) :: output(height, width)
        real(8), intent(in) :: low
        integer :: x, y, dx, dy, xx, yy
        logical :: changed

        changed = .false.

        do y = 2, height - 1
            do x = 2, width - 1
                if (output(y,x)) cycle
                if (input(y,x) < low) cycle

                do dy = -1, 1
                    do dx = -1, 1
                        if (dx == 0 .and. dy == 0) cycle
                        xx = x + dx
                        yy = y + dy
                        if (output(yy,xx)) then
                            output(y,x) = .true.
                            changed = .true.
                        end if
                    end do
                end do
            end do
        end do

        grow_edges = changed
    end function grow_edges


    subroutine write_json(path, edge_map, visited, width, height)
        character(len=*), intent(in) :: path
        integer, intent(in) :: width, height
        logical, intent(in) :: edge_map(height, width)
        logical, intent(inout) :: visited(height, width)
        integer :: unit, ios, x, y, id, count
        integer, allocatable :: points_x(:), points_y(:)

        open(newunit=unit, file=path, status='replace', action='write', &
             iostat=ios)
        if (ios /= 0) error stop 'cannot open output JSON'

        write(unit, '(A,I0,A,I0,A)') '{ "width": ', width, &
            ', "height": ', height, ', "edges": ['

        id = 0
        do y = 1, height
            do x = 1, width
                if (.not. edge_map(y,x) .or. visited(y,x)) cycle

                id = id + 1
                call collect_contour(edge_map, visited, x, y, width, height, &
                                      points_x, points_y, count)

                if (id > 1) write(unit, '(A)') ','
                write(unit, '(A,I0,A)') '  { "id": ', id, ', "points": ['

                call write_points(unit, points_x, points_y, count)
                write(unit, '(A)') '  ] }'

                deallocate(points_x, points_y)
            end do
        end do

        write(unit, '(A)') '] }'
        close(unit)
    end subroutine write_json


    subroutine collect_contour(edge_map, visited, start_x, start_y, width, height, &
                               points_x, points_y, count)
        integer, intent(in) :: start_x, start_y, width, height
        logical, intent(in) :: edge_map(height, width)
        logical, intent(inout) :: visited(height, width)
        integer, allocatable, intent(out) :: points_x(:), points_y(:)
        integer, intent(out) :: count
        integer, allocatable :: stack_x(:), stack_y(:)
        integer :: top, x, y, dx, dy, xx, yy, max_points

        max_points = width * height
        allocate(points_x(max_points), points_y(max_points))
        allocate(stack_x(max_points), stack_y(max_points))

        count = 0
        top = 1
        stack_x(top) = start_x
        stack_y(top) = start_y
        visited(start_y,start_x) = .true.

        do while (top > 0)
            x = stack_x(top)
            y = stack_y(top)
            top = top - 1

            count = count + 1
            points_x(count) = x - 1
            points_y(count) = y - 1

            do dy = 1, -1, -1
                do dx = 1, -1, -1
                    if (dx == 0 .and. dy == 0) cycle
                    xx = x + dx
                    yy = y + dy

                    if (xx < 1 .or. xx > width .or. yy < 1 .or. yy > height) cycle
                    if (.not. edge_map(yy,xx) .or. visited(yy,xx)) cycle

                    visited(yy,xx) = .true.
                    top = top + 1
                    stack_x(top) = xx
                    stack_y(top) = yy
                end do
            end do
        end do

        call shrink_points(points_x, points_y, count)
        deallocate(stack_x, stack_y)
    end subroutine collect_contour


    subroutine shrink_points(x, y, count)
        integer, allocatable, intent(inout) :: x(:), y(:)
        integer, intent(in) :: count
        integer, allocatable :: tx(:), ty(:)

        allocate(tx(count), ty(count))
        tx = x(1:count)
        ty = y(1:count)
        call move_alloc(tx, x)
        call move_alloc(ty, y)
    end subroutine shrink_points


    subroutine write_points(unit, x, y, count)
        integer, intent(in) :: unit, x(:), y(:), count
        integer :: i

        do i = 1, count
            if (i > 1) write(unit, '(A)', advance='no') ', '
            write(unit, '(A,I0,A,I0,A)', advance='no') &
                '{ "x": ', x(i), ', "y": ', y(i), ' }'
        end do
        write(unit, *)
    end subroutine write_points

end program csv2json
